{
  "Header": {
    "Original": "CVE-2022-2996 (A flaw was found in the python-scciclient when making an HTTPS connect ...)",
    "Line": 28819,
    "ID": "CVE-2022-2996",
    "Description": "(A flaw was found in the python-scciclient when making an HTTPS connect ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-3180-1}",
      "Line": 28820,
      "Type": "xref",
      "Bugs": [
        "DLA-3180-1"
      ]
    },
    {
      "Original": "- python-scciclient 0.12.3-2 (bug #1018213)",
      "Line": 28821,
      "Type": "package",
      "Package": "python-scciclient",
      "Kind": "fixed",
      "Version": "0.12.3-2",
      "BugNo": 1018213
    },
    {
      "Original": "[bullseye] - python-scciclient \u003cno-dsa\u003e (Minor issue)",
      "Line": 28822,
      "Type": "package",
      "Release": "bullseye",
      "Package": "python-scciclient",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://opendev.org/x/python-scciclient/commit/274dca0344b65b4ac113d3271d21c17e970a636c (0.12)",
      "Line": 28823,
      "Type": "NOTE",
      "Description": "https://opendev.org/x/python-scciclient/commit/274dca0344b65b4ac113d3271d21c17e970a636c (0.12)"
    }
  ]
}