{
  "Header": {
    "Original": "CVE-2019-3859 (An out of bounds read flaw was discovered in libssh2 before 1.8.1 in t ...)",
    "Line": 276649,
    "ID": "CVE-2019-3859",
    "Description": "(An out of bounds read flaw was discovered in libssh2 before 1.8.1 in t ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4431-1 DLA-1730-3 DLA-1730-1}",
      "Line": 276650,
      "Type": "xref",
      "Bugs": [
        "DSA-4431-1",
        "DLA-1730-3",
        "DLA-1730-1"
      ]
    },
    {
      "Original": "- libssh2 1.8.0-2.1 (bug #924965)",
      "Line": 276651,
      "Type": "package",
      "Package": "libssh2",
      "Kind": "fixed",
      "Version": "1.8.0-2.1",
      "BugNo": 924965
    },
    {
      "Original": "NOTE: https://www.libssh2.org/CVE-2019-3859.html",
      "Line": 276652,
      "Type": "NOTE",
      "Description": "https://www.libssh2.org/CVE-2019-3859.html"
    },
    {
      "Original": "NOTE: Patch: https://libssh2.org/1.8.0-CVE/CVE-2019-3859.patch",
      "Line": 276653,
      "Type": "NOTE",
      "Description": "Patch: https://libssh2.org/1.8.0-CVE/CVE-2019-3859.patch"
    },
    {
      "Original": "NOTE: https://github.com/libssh2/libssh2/pull/315",
      "Line": 276654,
      "Type": "NOTE",
      "Description": "https://github.com/libssh2/libssh2/pull/315"
    }
  ]
}