{
  "Header": {
    "Original": "CVE-2021-41496 (** DISPUTED ** Buffer overflow in the array_from_pyobj function of for ...)",
    "Line": 92763,
    "ID": "CVE-2021-41496",
    "Description": "(** DISPUTED ** Buffer overflow in the array_from_pyobj function of for ...)"
  },
  "Annotations": [
    {
      "Original": "- numpy \u003cunfixed\u003e (unimportant)",
      "Line": 92764,
      "Type": "package",
      "Package": "numpy",
      "Kind": "unfixed",
      "Severity": "unimportant"
    },
    {
      "Original": "NOTE: https://github.com/numpy/numpy/issues/19000",
      "Line": 92765,
      "Type": "NOTE",
      "Description": "https://github.com/numpy/numpy/issues/19000"
    },
    {
      "Original": "NOTE: https://github.com/numpy/numpy/pull/20630",
      "Line": 92766,
      "Type": "NOTE",
      "Description": "https://github.com/numpy/numpy/pull/20630"
    },
    {
      "Original": "NOTE: https://github.com/numpy/numpy/commit/271010f1037150e95017f803f4214b8861e528f2",
      "Line": 92767,
      "Type": "NOTE",
      "Description": "https://github.com/numpy/numpy/commit/271010f1037150e95017f803f4214b8861e528f2"
    }
  ]
}