{
  "Header": {
    "Original": "CVE-2020-8315 (In Python (CPython) 3.6 through 3.6.10, 3.7 through 3.7.6, and 3.8 thr ...)",
    "Line": 209520,
    "ID": "CVE-2020-8315",
    "Description": "(In Python (CPython) 3.6 through 3.6.10, 3.7 through 3.7.6, and 3.8 thr ...)"
  },
  "Annotations": [
    {
      "Original": "- python3.8 \u003cnot-affected\u003e (Windows-specific)",
      "Line": 209521,
      "Type": "package",
      "Package": "python3.8",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "- python3.7 \u003cnot-affected\u003e (Windows-specific)",
      "Line": 209522,
      "Type": "package",
      "Package": "python3.7",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "NOTE: https://bugs.python.org/issue39401",
      "Line": 209523,
      "Type": "NOTE",
      "Description": "https://bugs.python.org/issue39401"
    }
  ]
}