{
  "Header": {
    "Original": "CVE-2022-2850 (A flaw was found In 389-ds-base. When the Content Synchronization plug ...)",
    "Line": 29050,
    "ID": "CVE-2022-2850",
    "Description": "(A flaw was found In 389-ds-base. When the Content Synchronization plug ...)"
  },
  "Annotations": [
    {
      "Original": "- 389-ds-base \u003cunfixed\u003e (bug #1018054)",
      "Line": 29051,
      "Type": "package",
      "Package": "389-ds-base",
      "Kind": "unfixed",
      "BugNo": 1018054
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2118691",
      "Line": 29052,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2118691"
    },
    {
      "Original": "NOTE: https://github.com/389ds/389-ds-base/issues/4711#issuecomment-1205100979",
      "Line": 29053,
      "Type": "NOTE",
      "Description": "https://github.com/389ds/389-ds-base/issues/4711#issuecomment-1205100979"
    },
    {
      "Original": "NOTE: https://github.com/389ds/389-ds-base/issues/5418",
      "Line": 29054,
      "Type": "NOTE",
      "Description": "https://github.com/389ds/389-ds-base/issues/5418"
    },
    {
      "Original": "NOTE: https://github.com/389ds/389-ds-base/commit/513a763b551848e5532ec22bb0086464aa09252f (main)",
      "Line": 29055,
      "Type": "NOTE",
      "Description": "https://github.com/389ds/389-ds-base/commit/513a763b551848e5532ec22bb0086464aa09252f (main)"
    },
    {
      "Original": "NOTE: https://github.com/389ds/389-ds-base/commit/19632a4b8de5ba0abe05cdfe514a7ada07d0c299 (389-ds-base-2.0)",
      "Line": 29056,
      "Type": "NOTE",
      "Description": "https://github.com/389ds/389-ds-base/commit/19632a4b8de5ba0abe05cdfe514a7ada07d0c299 (389-ds-base-2.0)"
    },
    {
      "Original": "NOTE: https://github.com/389ds/389-ds-base/commit/be599560c9bbb17570f5eeb5aac1919a8d333567 (389-ds-base-1.4.4)",
      "Line": 29057,
      "Type": "NOTE",
      "Description": "https://github.com/389ds/389-ds-base/commit/be599560c9bbb17570f5eeb5aac1919a8d333567 (389-ds-base-1.4.4)"
    },
    {
      "Original": "NOTE: https://github.com/389ds/389-ds-base/commit/bd566957f85c889f13cd24f903c91c16c955acbd (389-ds-base-1.3.10)",
      "Line": 29058,
      "Type": "NOTE",
      "Description": "https://github.com/389ds/389-ds-base/commit/bd566957f85c889f13cd24f903c91c16c955acbd (389-ds-base-1.3.10)"
    },
    {
      "Original": "NOTE: Results from an incomplete fix for CVE-2021-3514",
      "Line": 29059,
      "Type": "NOTE",
      "Description": "Results from an incomplete fix for CVE-2021-3514"
    }
  ]
}