{
  "Header": {
    "Original": "CVE-2021-25293 (An issue was discovered in Pillow before 8.1.1. There is an out-of-bou ...)",
    "Line": 135966,
    "ID": "CVE-2021-25293",
    "Description": "(An issue was discovered in Pillow before 8.1.1. There is an out-of-bou ...)"
  },
  "Annotations": [
    {
      "Original": "- pillow 8.1.1-1",
      "Line": 135967,
      "Type": "package",
      "Package": "pillow",
      "Kind": "fixed",
      "Version": "8.1.1-1"
    },
    {
      "Original": "[buster] - pillow \u003cignored\u003e (Minor issue)",
      "Line": 135968,
      "Type": "package",
      "Release": "buster",
      "Package": "pillow",
      "Kind": "ignored",
      "Description": "Minor issue"
    },
    {
      "Original": "[stretch] - pillow \u003cnot-affected\u003e (Vulnerable code introduced later)",
      "Line": 135969,
      "Type": "package",
      "Release": "stretch",
      "Package": "pillow",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduced later"
    },
    {
      "Original": "NOTE: https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html",
      "Line": 135970,
      "Type": "NOTE",
      "Description": "https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html"
    },
    {
      "Original": "NOTE: https://github.com/python-pillow/Pillow/commit/f891baa604636cd2506a9360d170bc2cf4963cc5",
      "Line": 135971,
      "Type": "NOTE",
      "Description": "https://github.com/python-pillow/Pillow/commit/f891baa604636cd2506a9360d170bc2cf4963cc5"
    },
    {
      "Original": "NOTE: Introduced in https://github.com/python-pillow/Pillow/commit/a90dc4910045f5c6c119b582d4fd2e4841cd51f8 (v4.3.0)",
      "Line": 135972,
      "Type": "NOTE",
      "Description": "Introduced in https://github.com/python-pillow/Pillow/commit/a90dc4910045f5c6c119b582d4fd2e4841cd51f8 (v4.3.0)"
    }
  ]
}