{
  "Header": {
    "Original": "CVE-2021-3426 (There's a flaw in Python 3's pydoc. A local or adjacent attacker who d ...)",
    "Line": 128617,
    "ID": "CVE-2021-3426",
    "Description": "(There's a flaw in Python 3's pydoc. A local or adjacent attacker who d ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2619-1}",
      "Line": 128618,
      "Type": "xref",
      "Bugs": [
        "DLA-2619-1"
      ]
    },
    {
      "Original": "[experimental] - python3.9 3.9.3-1",
      "Line": 128619,
      "Type": "package",
      "Release": "experimental",
      "Package": "python3.9",
      "Kind": "fixed",
      "Version": "3.9.3-1"
    },
    {
      "Original": "- python3.9 3.9.7-1",
      "Line": 128620,
      "Type": "package",
      "Package": "python3.9",
      "Kind": "fixed",
      "Version": "3.9.7-1"
    },
    {
      "Original": "[bullseye] - python3.9 \u003cno-dsa\u003e (Minor issue)",
      "Line": 128621,
      "Type": "package",
      "Release": "bullseye",
      "Package": "python3.9",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "- python3.7 \u003cremoved\u003e",
      "Line": 128622,
      "Type": "package",
      "Package": "python3.7",
      "Kind": "removed"
    },
    {
      "Original": "[buster] - python3.7 \u003cno-dsa\u003e (Minor issue)",
      "Line": 128623,
      "Type": "package",
      "Release": "buster",
      "Package": "python3.7",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "- python3.5 \u003cremoved\u003e",
      "Line": 128624,
      "Type": "package",
      "Package": "python3.5",
      "Kind": "removed"
    },
    {
      "Original": "- python2.7 \u003cnot-affected\u003e (Vulnerable code not present)",
      "Line": 128625,
      "Type": "package",
      "Package": "python2.7",
      "Kind": "not-affected",
      "Description": "Vulnerable code not present"
    },
    {
      "Original": "- pypy3 7.3.3+dfsg-4",
      "Line": 128626,
      "Type": "package",
      "Package": "pypy3",
      "Kind": "fixed",
      "Version": "7.3.3+dfsg-4"
    },
    {
      "Original": "[buster] - pypy3 \u003cno-dsa\u003e (Minor issue)",
      "Line": 128627,
      "Type": "package",
      "Release": "buster",
      "Package": "pypy3",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://bugs.python.org/issue42988",
      "Line": 128628,
      "Type": "NOTE",
      "Description": "https://bugs.python.org/issue42988"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/9b999479c0022edfc9835a8a1f06e046f3881048",
      "Line": 128629,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/9b999479c0022edfc9835a8a1f06e046f3881048"
    },
    {
      "Original": "NOTE: https://python-security.readthedocs.io/vuln/pydoc-getfile.html",
      "Line": 128630,
      "Type": "NOTE",
      "Description": "https://python-security.readthedocs.io/vuln/pydoc-getfile.html"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/pull/24337",
      "Line": 128631,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/pull/24337"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/pull/24285",
      "Line": 128632,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/pull/24285"
    }
  ]
}