{
  "affected_release": [
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2021-05-18T00:00:00Z",
      "advisory": "RHSA-2021:1853",
      "package": "unbound-0:1.7.3-15.el8",
      "cpe": "cpe:/a:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8.2 Extended Update Support",
      "release_date": "2022-02-22T00:00:00Z",
      "advisory": "RHSA-2022:0632",
      "package": "unbound-0:1.7.3-12.el8_2",
      "cpe": "cpe:/a:redhat:rhel_eus:8.2"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "unbound",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "unbound",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "unbound",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2019-12-11T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2019-25036 unbound: assertion failure and denial of service in synth_cname",
    "id": "1954782",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1954782"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "9.8",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    "status": "verified"
  },
  "iava": "",
  "cwe": "CWE-617-\u003eCWE-787",
  "statement": "This issue could not be triggered by running unbound regularly, but only by injecting the packet directly to the vulnerable function through fuzzing. For this reason its Impact is Moderate. Upstream has also disputed this CVE.",
  "acknowledgement": "",
  "name": "CVE-2019-25036",
  "document_distribution": "",
  "details": [
    "** DISPUTED ** Unbound before 1.9.5 allows an assertion failure and denial of service in synth_cname. NOTE: The vendor disputes that this is a vulnerability. Although the code may be vulnerable, a running Unbound installation cannot be remotely or locally exploited.",
    "A flaw was found in unbound. A reachable assertion in the synth_cname function can be triggered by sending invalid packets to the server. If asserts are disabled during compilation, this issue might lead to an out-of-bounds write in dname_pkt_copy function. The highest threat from this vulnerability is to data confidentiality and integrity as well as service availability."
  ],
  "references": null
}